version: '3'

services:
  nginx:
    image: nginx:stable
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
    environment:
      - TZ=Asia/Tokyo
      - WRONG_HOST=www.napple.team
      - TRUES_HOST=napple.team
    command: /bin/bash -c "envsubst '$$WRONG_HOST$$TRUES_HOST' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
